### ISSUE TITLE
Bring GeoInterface concrete types over here

### ISSUE THREAD

**Issue by visr** [JuliaGeo/GeoJSON.jl#21]
The concrete types in GeoInterface.jl were written initially for this package and thus are a pretty good match. But if we want GeoInterface to support a wide selection of concrete types we probably need to move to an approach similar to Tables.jl, meaning we can take the concrete types out of GeoInterface.jl

Step one would be to move the types more or less as is. But possibly we directly switch the concrete types over to GeometryTypes, as suggested in https://github.com/JuliaGeo/GeoInterface.jl/issues/24?

**Comment by yeesian** [comment]
> But possibly we directly switch the concrete types over to GeometryTypes, as suggested in JuliaGeo/GeoInterface.jl#24?

If it's possible, I'm on board with that

**Comment by visr** [comment]
Rather than using GeometryTypes it would probably make more sense to switch directly to [GeometryBasics](https://github.com/SimonDanisch/GeometryBasics.jl), see https://github.com/JuliaGeometry/GeometryTypes.jl/pull/166#issuecomment-518713253.

**Comment by visr** [comment]
I'll close this. Rather than taking this gradual step, it would probably be better to address this when we switch to the new GeoInterface being drafted in https://github.com/yeesian/GeoInterfaceRFC.jl.
