### ISSUE TITLE
Handle GeoFormatTypes `GeoJSON` objects

### ISSUE THREAD

**Issue by rafaqz** [JuliaGeo/GeoJSON.jl#32]
It would be good if an object we already know is `GeoFormatTypes.GeoJSON` would pass through `GeoJSON.write`. It will already be a `Dict` or `String`. The string is assumed to be correctly formatted JSON so would not need anything done. A `Dict` would go to `JSON3.write`.

We could even wrap the output as a GeoJSON string, but maybe that's going to far for now... It would be like `JSString` in WebIO.jl that wraps javascipt strings.

The use case for this is to allow users to pass in various objects that need different degrees of processing to be formatted as GeoJSON, and they all work.

**Comment by rafaqz** [comment]
Totally forgot about this. @yeesian the `GeoJSON` wrapper is explicitly saying that the internal string follows the GeoJSON standard, that's basically all that it does. But I will make this clearer in the docs, I'm putting some time into that currently.

**Comment by yeesian** [comment]
The documentation and state of GeoFormatTypes.jl has improved quite a bit since https://github.com/JuliaGeo/GeoJSON.jl/issues/32#issuecomment-953463705 (really great work!) and I agree it will be nice for this package.

**Comment by visr** [comment]
Fixed by #42.
