### ISSUE TITLE
Widen the scope of `GeoJSON.write`

### ISSUE THREAD

**Issue by rafaqz** [JuliaGeo/GeoJSON.jl#34]
It seems that `write` does not work with all `AbstractGeometry`. I'm not sure if that is intentional. But currently e.g. `ArchGDAL.IGeometry` does not work.

```julia
julia> using GADM, GeoJSON

julia> GeoJSON.write(GADM.get("MUS").geom[1])
ERROR: MethodError: no method matching write(::ArchGDAL.IGeometry{ArchGDAL.wkbMultiPolygon})
Closest candidates are:
  write(::AbstractFeatureCollection) at ~/.julia/packages/GeoJSON/JVqvX/src/GeoJSON.jl:40
  write(::AbstractGeometryCollection) at ~/.julia/packages/GeoJSON/JVqvX/src/GeoJSON.jl:40
  write(::AbstractFeature) at ~/.julia/packages/GeoJSON/JVqvX/src/GeoJSON.jl:40
  ...
Stacktrace:
 [1] top-level scope
   @ REPL[33]:1
```

In the docs we say that any `AbstractGeometry` will work:

```julia
help?> GeoJSON.write
  write(obj)

  Create a GeoJSON string from an object that implements the GeoInterface, either AbstractGeometry,
  AbstractFeature or AbstractFeatureCollection.
```

The current workaround is to wrap in a `Feature`.

**Comment by rafaqz** [comment]
Is there a reason we have a limited list of types dispatched on here, instead of just using `AbstractGeometry` ?
https://github.com/JuliaGeo/GeoJSON.jl/blob/master/src/GeoJSON.jl#L53-L57

**Comment by visr** [comment]
I think that can indeed just be `AbstractGeometry`. As far as I can see all of the current GeoInterface subtypes of `AbstractGeometry` are supported by the GeoJSON format. `ArchGDAL.IGeometry` should work through `geo2dict`.

**Comment by visr** [comment]
The example above, `GeoJSON.write(GADM.get("MUS").geom[1])`, now works, since #42. We still need to test this however. Currently only objects from this package are tested. We could test with GADM/ArchGDAL, or perhaps just something small like https://github.com/evetion/WellKnownGeometry.jl.

**Comment by rafaqz** [comment]
Yes it would be nice to test this. Leaflet.jl already tests it with GADM.jl, so maybe WellKnownGeometry.jl.

**Comment by rafaqz** [comment]
This works now
