### ISSUE TITLE
Migration to JuliaGeo

### ISSUE THREAD

**Issue by garborg** [JuliaGeo/GeoJSON.jl#4]
Migration steps:
- [x] Transfer ownership to org
- [x] Flip on coveralls for org (I think Travis is smart enough to handle the transfer automatically)
- [x] Update urls in README
- [ ] Next time a version is tagged in METADATA, update the url as part of PR

**Comment by yeesian** [comment]
Okay, I'm reasonably happy with the progress, and think the bug-fixes (and slight changes to the interface) are worth pushing a patch to METADATA. Shall I tag it and submit another PR?

**Comment by garborg** [comment]
Sounds good. Liking the pace of development :)

**Comment by yeesian** [comment]
closed by https://github.com/JuliaLang/METADATA.jl/pull/2048
