### ISSUE TITLE
Incompatibility with trait-based interfaces in GeoInterface 1.0

### ISSUE THREAD

**Issue by truedichotomy** [JuliaGeo/GeoJSON.jl#40]
GeoInterface 1.0 has breaking change that does not work with current version of GeoJSON (v0.5.1).

**Comment by visr** [comment]
That's right. For this package in particular GeoInterface v1 is very breaking. See #36 for thoughts on how to proceed with this package.

**Comment by rafaqz** [comment]
GeoJSONTables.jl is close to being a replacement now. I'm just implementing `write` so its fully functional. 

There are a lot of packages to transition for GeoInterfsce 1.0, so have some patience as its mostly 2 people doing these updates, on top of our other regular jobs.

**Comment by visr** [comment]
Fixed by #42.
