### ISSUE TITLE
Provide a high-level GeoJSON.Table(fname)

### ISSUE THREAD

**Issue by juliohm** [JuliaGeo/GeoJSON.jl#49]
Similar to Shapefiles.jl it would be more user-friendly. Currently we have to read the file with Base.read and then read it again with GeoJSON.read.

**Comment by rafaqz** [comment]
Good idea. Feel free to PR or I will add it next week.

**Comment by visr** [comment]
Looks like we'll be getting this for free in https://github.com/quinnj/JSON3.jl/pull/243, making `GeoJSON.read` also work for paths.
