### ISSUE TITLE
Support of http access 

### ISSUE THREAD

**Issue by alex-s-gardner** [JuliaGeo/GeoJSON.jl#56]
It would be nice if `GeoJSON.read()` could accept a URL, e.g. "https://its-live-data.s3.amazonaws.com/datacubes/catalog_v02.json"

**Comment by visr** [comment]
I'd just use HTTP separately, it only adds one line of code:

```
using GeoJSON, HTTP

resp = HTTP.get("https://its-live-data.s3.amazonaws.com/datacubes/catalog_v02.json")
fc = GeoJSON.read(resp.body)
```

Otherwise we'd have to take on a dependency on HTTP.

**Comment by alex-s-gardner** [comment]
Ya, that makes sense. I got lost with trying:

```
resp = HTTP.get("https://its-live-data.s3.amazonaws.com/datacubes/catalog_v02.json")
fc = GeoJSON.read(resp)
```
Maybe I can add an example to the `ReadMe`

**Comment by visr** [comment]
Yes that'd be welcome!

**Comment by likev** [comment]
I just create a pull request https://github.com/JuliaGeo/GeoJSON.jl/pull/90 so that we can use Downloads.download in stdlib
```julia
using GeoJSON, Downloads
io = Downloads.download("https://its-live-data.s3.amazonaws.com/datacubes/catalog_v02.json", IOBuffer())
fc = GeoJSON.read(io)
```
