### ISSUE TITLE
Provide support for Geospatial Operations?

### ISSUE THREAD

**Issue by yeesian** [JuliaGeo/GeoJSON.jl#6]
I had been porting the functionality for [Turf](https://github.com/Turfjs/turf) in a [separate repository](https://github.com/yeesian/Turf.jl), but that codebase had been designed for javascript apps, and there's [significant] overlap in functionality with DataFrames-type operations, and other packages (in interpolations, etc).

Does it make sense to
- support a small set of core operations (union/convexhull/within/etc) on individual geometries in GeoJSON.jl, and
- use DataFrames.jl (see https://github.com/JuliaGeo/GeoJSON.jl/pull/5) to perform more sophisticated queries/operations?

If so, I'll migrate the relevant portions of the code over from Turf.jl to this repo (to `src/turf.jl`) through a PR. Your thoughts?

cc @garborg

**Comment by garborg** [comment]
@yeesian My thought is that GeoJSON.jl should stay light, basically i/o only, (eventually have types moved out elsewhere, where supported geometries and features may be a superset of what GeoJSON supports, and that  new package (`GeoShapes.jl`, or whatever) will be a dependency of GeoJSON.jl as well as of packages that handle i/o of shapefiles, kml, etc.), and that those core operations (convexhull, etc.) would be either in the new package, or in `Turf.jl`. Then analysis w/o DataFrames both depend on those same core functions.

**Comment by yeesian** [comment]
Okay, I've been independently converging towards the same design too. See https://github.com/yeesian/GeoInterface.jl.

**Comment by garborg** [comment]
That sounds great! I've done some work making `Geodesy.jl` more powerful, too -- if I can finish a couple things there soon, I'll try to come experiment on the interface with you soon.

**Comment by yeesian** [comment]
I saw, and have provided an [AbstractPosition](https://github.com/yeesian/GeoInterface.jl/blob/master/src/GEOInterface.jl#L36-L45) in anticipation (:

**Comment by garborg** [comment]
Ah, cool! I was wondering how that would work but hadn't stopped to try to puzzle it out yet.

**Comment by yeesian** [comment]
It's meant to replace code like `type XYZ`[here](https://github.com/JuliaGeo/Geodesy.jl/blob/master/src/points.jl#L73-L94), for subsequent code to be able to

- deal with `ENU`, `LLA`, `XYZ`, etc through an `AbstractPosition` interface
- be able to access individual coordinates through (i) getter methods (`x`,`y`,`z`), or (ii) an array-like interface

I have provided an [example implementation](https://github.com/JuliaGeo/GeoJSON.jl/blob/geo-interface/src/types.jl#L17-L24) in `GeoJSON.jl`.
