### ISSUE TITLE
geojson strips 'properties' field from a feature

### ISSUE THREAD

**Issue by jlewis91** [JuliaGeo/GeoJSON.jl#7]
When converting a geoJSON object to either a dict or printing a json string, the "properties" element of each Feature seems not to be included.

```
a = """{
    "properties": {
        "Ã": "Ã"
    },
    "type": "Feature",
    "geometry": null,
    "crs": {
        "type": "link",
        "properties": {
            "href": "data.crs",
            "type": "ogcwkt"
        }
    }
}"""

a = GeoJSON.parse(a)
geojson(a)
```
output:
```
"{\"geometry\":null,\"type\":\"Feature\",\"crs\":{\"properties\":{\"href\":\"data.crs\",\"type\":\"ogcwkt\"},\"type\":\"link\"}}"
```

**Comment by yeesian** [comment]
That's embarrassing.. thanks!

**Comment by yeesian** [comment]
I'm sorry I forgot it's not tagged yet; re-opening this issue. If you're waiting for the fix, you can do `Pkg.checkout("GeoJSON")` to fetch the latest changes from master.

**Comment by yeesian** [comment]
closed by https://github.com/JuliaLang/METADATA.jl/pull/5406
